// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ekbaya/asham/pkg/db/repository"
	"github.com/ekbaya/asham/pkg/domain/services"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitializeServices(db *gorm.DB) (*services.ServiceContainer, error) {
	organizationRepository := repository.NewOrganizationRepository(db)
	organizationService := services.NewOrganizationService(organizationRepository)
	memberRepository := repository.NewMemberRepository(db)
	memberService := services.NewMemberService(memberRepository)
	projectRepository := repository.NewProjectRepository(db)
	projectService := services.NewProjectService(projectRepository)
	documentRepository := repository.NewDocumentRepository(db)
	documentService := services.NewDocumentService(documentRepository)
	serviceContainer := services.NewServiceContainer(organizationService, memberService, projectService, documentService)
	return serviceContainer, nil
}
