version: "3"

services:
  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 8081:80 # Expose Nextcloud on port 8081
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      NEXTCLOUD_TRUSTED_DOMAINS: collabo.arso.mystock.co.ke

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    ports:
      - 9980:9980 # Still required for internal Docker use and reverse proxy
    environment:
      - domain=collabo\\.arso\\.mystock\\.co\\.ke
      - username=admin
      - password=your-password
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - dictionaries=en_US
    cap_add:
      - MKNOD
    depends_on:
      - app

volumes:
  db:
  nextcloud:
